#!/usr/bin/evn sh
########################################
#  Tips taken from https://gist.github.com/2260182  #
########################################

# Helper function
write(){ defaults write "$@";};

# Enable full keyboard access for all controls (enable Tab in modal dialogs)
write NSGlobalDomain AppleKeyboardUIMode -int 3

# Enable sub-pixel font rendering on non-Apple LCDs
write NSGlobalDomain AppleFontSmoothing -int 2

# Enable iTunes track notifications in the Dock
write com.apple.dock itunes-notifications -bool true

# Allow quitting Finder via CMD + Q; helpful for hiding desktop icons
write com.apple.finder QuitMenuItem -bool true

# Show all filename extensions in Finder
write NSGlobalDomain AppleShowAllExtensions -bool true

# Use current directory as default search scope in Finder
write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Show Path bar in Finder
write com.apple.finder ShowPathbar -bool true

# Show Status bar in Finder
write com.apple.finder ShowStatusBar -bool true

# Expand save panel by default
write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Expand print panel by default
write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

# Disable "Are you sure you want to open this application?" dialog
write com.apple.LaunchServices LSQuarantine -bool false

# Disable shadow in screenshots
write com.apple.screencapture disable-shadow -bool true

# Enable highlight hover effect for the grid view of a stack (Dock)
write com.apple.dock mouse-over-hilite-stack -bool true

# Enable spring loading for all Dock items
write com.apple.dock enable-spring-load-actions-on-all-items -bool true

# Show indicator lights for open applications on the Dock
write com.apple.dock show-process-indicators -bool true

# Disable press-and-hold for keys in favor of key repeat
write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a faster keyboard repeat rate (altered to not be stupidly fast)
write NSGlobalDomain KeyRepeat -int 4

# Set a shorter delay until key repeat (also altered)
write NSGlobalDomain InitialKeyRepeat -int 10

# Disable auto-correct
write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Enable AirDrop over Ethernet and on unsupported Macs running Lion
write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Disable disk image verification
write com.apple.frameworks.diskimages skip-verify -bool true
write com.apple.frameworks.diskimages skip-verify-locked -bool true
write com.apple.frameworks.diskimages skip-verify-remote -bool true

# Automatically open a new Finder window when a volume is mounted
write com.apple.frameworks.diskimages auto-open-ro-root -bool true
write com.apple.frameworks.diskimages auto-open-rw-root -boot true
write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# Display full POSIX path as Finder window title
write com.apple.finder _FXShowPosixPathInTitle -bool true

# Increase window resize speed for Cocoa applications
write NSGlobalDomain NSWindowResizeTime -float 0.001

# Avoid creating .DS_Store files on network volumes
write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable the warning when changing file extension
write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Show item info under Desktop icons
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

# Enable snap-to-grid for Desktop icons
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

# Disable the warning when emptying the Trash
write com.apple.finder WarnOnEmptyTrash -bool false

# Require password 5 seconds after sleep or screen saver starts
write com.apple.screensaver askForPassword -int 1
write com.apple.screensaver askForPasswordDelay -int 5

# Enable Tap to Click (Trackpad)
write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

# Enable Safari's debug menu
write com.apple.Safari IncludeInternalDebugMenu -bool true

# Only use UTF-8 in Terminal.app
write com.apple.terminal StringEncodings -array 4

# Disable the Ping sidebar in iTunes
write com.apple.iTunes disablePingSidebar -bool true

# Disable all other Ping stuff in iTunes
write com.apple.iTunes disablePing -bool true

# Make CMD + F focus on search bar in iTunes
write com.apple.iTunes NSUserKeyEquivalents -dict-add "Target Search Field" "@F"

# Disable the "Reopen windows when logging back in" option (this works, but checkbox appears to be checked, disregard it)
write com.apple.loginwindow TALLogoutSavesState -bool false
write com.apple.loginwindow LoginWindowLaunchesRelaunchApps -bool false

# Reset Launchpad
test -e ~/Library/Application\ Support/Dock/*.db && rm ~/Library/Application\ Support/Dock/*.db

# Show the hidden ~/Library folder
chflags nohidden ~/Library

# Disable local Time Machine backups (requires admin access)
hash tmutil &>/dev/null && sudo tmutil disablelocal

###############################################################
#  For all changes to take effect, you must either logout or restart your computer.  #
###############################################################
